image: atlassian/default-image:4

clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Mirror main to GitHub
          script:
            - git push --force git@github.com:sentiance/sentiance.sdk.sample-apps-expo.git "refs/remotes/origin/main:refs/heads/main"
